apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: set-datadir-perms
          image: docker.io/grafana/grafana:8.2.6
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
          command:
            - sh
            - -c
            - |
              chown -R grafana /var/lib/grafana
              chmod -R ug+rwX /var/lib/grafana
          securityContext:
            runAsUser: 0
        - name: provision-dashboards
          image: docker.io/grafana/grafana:8.2.6
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
          command:
            - /bin/sh
            - -c
            - |
              apk add --update git
              cd /var/lib/grafana
              if [ ! -d dashboards ]; then
                git clone https://github.com/larsks/grafana-dashboards dashboards
              else
                git -C dashboards diff
                git -C dashboards checkout --force HEAD
                git -C dashboards pull --force --rebase
              fi
          securityContext:
            runAsUser: 0
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:8.2.6
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: provision-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: provision-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
          envFrom:
            - configMapRef:
                name: grafana-config
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
        - name: provision-datasources
          configMap:
            name: provision-datasources
        - name: provision-dashboards
          configMap:
            name: provision-dashboards
