apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

commonLabels:
  app: monitoring

resources:
  - namespaces/prometheus.yaml
  - ingress/monitoring.yaml

  - prometheus
  - grafana
  - snmp-exporter
  - thanos
  - weather-metrics

secretGenerator:
  - name: thanos-bucket-config
    files:
      - bucket-config.yaml=config/thanos-bucket-config.yaml
