apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

commonLabels:
  app: monitoring

resources:
  - namespaces/prometheus.yaml
  - sealedsecrets/thanos-bucket-config.sealed.yaml
  - middlewares/redirect-to-grafana.yaml
  - ingress/monitoring.yaml

  - prometheus
  - grafana
  - snmp-exporter
  - thanos
