apiVersion: apps/v1
kind: Deployment
metadata:
  name: sflow
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sflow
          image: docker.io/sflow/prometheus
          ports:
            - name: http
              containerPort: 8008
            - name: sflow
              containerPort: 6343
              protocol: UDP
          args:
            - -Dsnmp.ifname=yes
