apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: prometheus

configMapGenerator:
  - name: prometheus-config
    files:
      - data/prometheus.yml

resources:
  - deployments/prometheus.yaml
  - persistentvolumeclaims/prometheus-data.yaml
  - services/prometheus.yaml
  - services/thanos-sidecar-grpc.yaml
  - services/thanos-sidecar-http.yaml
