apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirector
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: redirector
          image: docker.io/alpinelinux/darkhttpd
          ports:
            - containerPort: 8080
          args:
            - --forward-all
            - http://monitoring.internal/grafana
