apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: snmp-exporter

resources:
  - deployments/snmp-exporter.yaml
  - persistentvolumeclaims/generator-config.yaml
  - services/snmp-exporter.yaml

configMapGenerator:
  - name: generator-data
    files:
      - data/generate-snmp-exporter-config.sh
