apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: thanos

resources:
- deployments/thanos-store.yaml
- deployments/thanos-query.yaml
- cronjobs/thanos-compact.yaml
- persistentvolumeclaims/thanos-store-data.yaml
- persistentvolumeclaims/thanos-compact-data.yaml
- services/thanos-store-grpc.yaml
- services/thanos-store-http.yaml
- services/thanos-query-http.yaml
