apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: weather-metrics

resources:
  - deployments/weather-metrics.yaml
  - services/weather-metrics.yaml

configMapGenerator:
  - name: weather-metrics-config
    files:
      - configs/config.json

secretGenerator:
  - name: weather-metrics-credentials
    envs:
      - secrets/weather-metrics-credentials.env
